return function()
  return {
    Normal = "editor",
    NormalNC = "editor.inactive",
    NormalFloat = "float",
    NormalSB = "editor.sidebar",
    FloatBorder = "float.border",
    EndOfBuffer = "editor.non.text",
    NonText = "editor.non.text",
    Whitespace = "editor.whitespace",
    Conceal = "foreground.muted",

    Cursor = "editor.cursor",
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    TermCursor = "editor.cursor",
    TermCursorNC = { fg = "foreground.muted", bg = "background.tertiary" },
    CursorLine = "editor.cursorline",
    CursorColumn = "editor.cursorline",
    CursorLineNr = "editor.cursorline.number",
    ColorColumn = "editor.color.column",
    QuickFixLine = "editor.cursorline",

    LineNr = "editor.line.number",
    SignColumn = { fg = "foreground.muted", bg = "background.editor" },
    SignColumnSB = { link = "SignColumn" },
    FoldColumn = { fg = "foreground.muted", bg = "background.editor" },
    Folded = "editor.fold",

    StatusLine = "chrome",
    StatusLineNC = "chrome.inactive",
    StatusLineTerm = "chrome",
    StatusLineTermNC = "chrome.inactive",
    TabLine = { fg = "foreground.secondary", bg = "background.secondary" },
    TabLineFill = { bg = "background.secondary" },
    TabLineSel = { fg = "foreground.primary", bg = "background.editor", style = "bold" },
    WildMenu = "popup.selected",

    WinSeparator = "editor.border",
    VertSplit = "editor.border",
    MsgSeparator = "float.border",

    Pmenu = "popup",
    PmenuSel = "popup.selected",
    PmenuSbar = "popup.scrollbar",
    PmenuThumb = "popup.thumb",
    PmenuMatch = { fg = "accent.literal", bg = "background.secondary", style = "bold" },
    PmenuMatchSel = { fg = "accent.literal", bg = "background.selection", style = "bold" },
    PmenuKind = { fg = "accent.quaternary", bg = "background.secondary" },
    PmenuKindSel = { fg = "accent.quaternary", bg = "background.selection" },
    PmenuExtra = { fg = "foreground.muted", bg = "background.secondary" },
    PmenuExtraSel = { fg = "foreground.muted", bg = "background.selection" },
    ComplMatchIns = "interaction.match",

    Search = "search",
    IncSearch = "search.active",
    CurSearch = "search.active",
    MatchParen = "search.match.paren",
    Visual = "visual",
    VisualNOS = "visual",

    ModeMsg = "message.mode",
    MoreMsg = "message",
    MsgArea = "message",
    WarningMsg = "message.warning",
    ErrorMsg = "message.error",
    Question = "message.question",

    SpellBad = { sp = "feedback.danger", style = "undercurl" },
    SpellCap = { sp = "feedback.info", style = "undercurl" },
    SpellRare = { sp = "accent.tertiary", style = "undercurl" },
    SpellLocal = { sp = "feedback.hint", style = "undercurl" },

    Directory = "entity.directory",
    Title = "foreground.strong",
    Todo = { fg = "feedback.warning", style = "bold" },
    Underlined = { style = "underline" },
    Bold = { style = "bold" },
    Italic = { style = "italic" },
    Ignore = {},
    Error = "diagnostic.error",

    DiffAdd = { bg = "background.feedback.success" },
    DiffDelete = { bg = "background.feedback.danger" },
    DiffChange = { bg = "background.feedback.warning" },
    DiffText = "diff.text",
    Added = "diff.add",
    Changed = "diff.change",
    Removed = "diff.delete",
    diffAdded = { link = "Added" },
    diffChanged = { link = "Changed" },
    diffRemoved = { link = "Removed" },
    diffOldFile = { fg = "feedback.warning" },
    diffNewFile = { fg = "accent.primary" },
    diffFile = { fg = "feedback.info" },
    diffLine = { fg = "accent.quaternary" },
    diffIndexLine = { fg = "feedback.warning" },
    qfLineNr = { link = "LineNr" },
    qfFileName = { link = "Directory" },

    DiagnosticError = "diagnostic.error",
    DiagnosticWarn = "diagnostic.warn",
    DiagnosticInfo = "diagnostic.info",
    DiagnosticHint = "diagnostic.hint",
    DiagnosticOk = "diagnostic.ok",
    DiagnosticUnderlineError = { sp = "feedback.danger", style = "undercurl" },
    DiagnosticUnderlineWarn = { sp = "feedback.warning", style = "undercurl" },
    DiagnosticUnderlineInfo = { sp = "feedback.info", style = "undercurl" },
    DiagnosticUnderlineHint = { sp = "feedback.hint", style = "undercurl" },
    DiagnosticUnderlineOk = { sp = "feedback.success", style = "undercurl" },
    DiagnosticVirtualTextError = "diagnostic.error",
    DiagnosticVirtualTextWarn = "diagnostic.warn",
    DiagnosticVirtualTextInfo = "diagnostic.info",
    DiagnosticVirtualTextHint = "diagnostic.hint",
    DiagnosticVirtualTextOk = "diagnostic.ok",
    DiagnosticSignError = "diagnostic.error",
    DiagnosticSignWarn = "diagnostic.warn",
    DiagnosticSignInfo = "diagnostic.info",
    DiagnosticSignHint = "diagnostic.hint",
    DiagnosticSignOk = "diagnostic.ok",
    DiagnosticFloatingError = { link = "DiagnosticError" },
    DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
    DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
    DiagnosticFloatingHint = { link = "DiagnosticHint" },
    DiagnosticFloatingOk = { link = "DiagnosticOk" },

    LspReferenceText = "reference",
    LspReferenceRead = "reference",
    LspReferenceWrite = "reference.write",
    LspSignatureActiveParameter = { bg = "background.selection", style = "bold" },
    LspCodeLens = "foreground.muted",
    LspCodeLensSeparator = { fg = "border.primary" },
    LspInlayHint = { fg = "foreground.muted", bg = "background.secondary" },
    LspInfoBorder = "float.border",
    LspInfoFiletype = "syntax.keyword",
    LspInfoList = "foreground.primary",
    LspInfoTip = "foreground.muted",
    LspInfoTitle = "foreground.strong",
  }
end
