return function()
  local buckets = require("neo-ds.syntax_buckets")
  local groups = {
    Comment = "syntax.comment",
    Constant = "syntax.constant",
    String = "syntax.string",
    Character = "syntax.string",
    Number = "syntax.number",
    Boolean = "syntax.boolean",
    Float = "syntax.number",
    Identifier = "syntax.variable",
    Function = "syntax.function",
    Statement = "syntax.keyword",
    Conditional = "syntax.keyword",
    Repeat = "syntax.keyword",
    Label = "syntax.keyword",
    Operator = "syntax.operator",
    Keyword = "syntax.keyword",
    Exception = "syntax.keyword",
    PreProc = "syntax.preprocessor",
    Include = "syntax.keyword.secondary",
    Define = "syntax.preprocessor",
    Macro = "syntax.preprocessor",
    PreCondit = "syntax.preprocessor",
    Type = "syntax.type",
    StorageClass = "syntax.keyword.secondary",
    Structure = "syntax.type",
    Typedef = "syntax.type",
    Special = "accent.quaternary",
    SpecialChar = "accent.quaternary",
    Tag = "syntax.tag",
    Delimiter = "syntax.punctuation",
    SpecialComment = { fg = "syntax.comment", style = "bold" },
    Debug = "diagnostic.error",

    htmlTag = "syntax.tag",
    htmlH1 = "syntax.markup.heading",
    htmlH2 = "syntax.markup.heading",
    xmlAttrib = { link = "htmlTag" },
    xmlTagName = { link = "htmlTag" },
    cssBraces = "syntax.punctuation",
    cssMedia = { link = "Keyword" },
    cssProp = { link = "Constant" },
    cssPseudoClassId = { link = "Function" },
    lessAmpersand = { link = "Function" },
    lessClass = { link = "Function" },
    lessClassCall = { link = "Function" },
    lessCssAttribute = { link = "Constant" },
    lessFunction = { link = "Constant" },
    lessVariable = "syntax.variable",
    jsonKeyword = "syntax.keyword",
    jsonNull = { link = "Constant" },
    luaFunction = { link = "Keyword" },
    yamlBlockMappingKey = "syntax.keyword",
    yamlFlowMappingKey = "syntax.keyword",
    markdownHeadingDelimiter = "syntax.markup.heading",
    markdownCode = "syntax.markup.raw",
    markdownCodeBlock = "syntax.markup.raw",
    markdownH1 = "syntax.markup.heading",
    markdownH2 = "syntax.markup.heading",
    markdownLinkText = "foreground.link",
    mkdHeading = "syntax.markup.heading",
    mkdCode = "syntax.markup.raw",
    mkdCodeDelimiter = "syntax.punctuation",
    mkdCodeStart = "syntax.punctuation",
    mkdCodeEnd = "syntax.punctuation",
    mkdLink = "foreground.link",

    pythonDecorator = "syntax.annotation",
    pythonDecoratorName = "syntax.annotation",
    pythonFunction = "syntax.function.definition",
    pythonConditional = "syntax.keyword",
    pythonRepeat = "syntax.keyword",
    pythonException = "syntax.keyword",
    pythonStatement = "syntax.keyword",
    pythonInclude = "syntax.keyword.secondary",
    pythonClass = "syntax.type",
    pythonType = "syntax.type",
    pythonAttribute = "syntax.property",
  }

  buckets.apply_syntax(groups)

  return groups
end
