return function()
  local buckets = require("neo-ds.syntax_buckets")
  local groups = {
    ["@none"] = {},
    ["@conceal"] = { link = "Conceal" },
    ["@error"] = { link = "Error" },
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "Comment" },
    ["@comment.todo"] = { fg = "feedback.warning", style = "bold" },
    ["@comment.error"] = { fg = "foreground.inverse", bg = "feedback.danger" },
    ["@comment.warning"] = { fg = "foreground.inverse", bg = "feedback.warning" },
    ["@comment.hint"] = { fg = "foreground.inverse", bg = "feedback.hint" },
    ["@comment.info"] = { fg = "foreground.inverse", bg = "feedback.info" },
    ["@string"] = "syntax.string",
    ["@string.documentation"] = { link = "String" },
    ["@string.escape"] = "accent.quaternary",
    ["@string.regexp"] = "accent.quaternary",
    ["@string.special"] = "accent.quaternary",
    ["@string.special.symbol"] = { link = "@constant" },
    ["@string.special.url"] = "foreground.link",
    ["@string.special.path"] = { fg = "accent.primary" },
    ["@number"] = "syntax.number",
    ["@number.float"] = { link = "Float" },
    ["@float"] = "syntax.number",
    ["@boolean"] = "syntax.boolean",
    ["@constant"] = "syntax.constant",
    ["@constant.builtin"] = "syntax.constant",
    ["@constant.macro"] = "syntax.preprocessor",
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@variable"] = "syntax.variable",
    ["@variable.builtin"] = "syntax.builtin",
    ["@variable.parameter"] = "syntax.variable",
    ["@variable.member"] = "syntax.property",
    ["@property"] = { link = "@variable.member" },
    ["@module"] = "syntax.variable",
    ["@module.builtin"] = "syntax.builtin",
    ["@namespace"] = "syntax.variable",
    ["@type"] = "syntax.type",
    ["@type.builtin"] = "syntax.builtin",
    ["@type.definition"] = "syntax.type.definition",
    ["@type.qualifier"] = "syntax.keyword.secondary",
    ["@attribute"] = "syntax.annotation",
    ["@function"] = "syntax.function.definition",
    ["@function.builtin"] = "syntax.function.call",
    ["@function.call"] = "syntax.function.call",
    ["@function.macro"] = "syntax.preprocessor",
    ["@function.method"] = "syntax.function.definition",
    ["@function.method.call"] = "syntax.function.call",
    ["@constructor"] = "syntax.function.call",
    ["@operator"] = "syntax.operator",
    ["@punctuation.delimiter"] = "syntax.punctuation",
    ["@punctuation.bracket"] = "syntax.bracket",
    ["@punctuation.special"] = "syntax.punctuation",
    ["@punctuation.special.annotation"] = "accent.note",
    ["@keyword.conditional.ternary"] = { link = "@keyword" },
    ["@tag"] = "syntax.tag",
    ["@tag.builtin"] = { link = "@tag" },
    ["@tag.attribute"] = "syntax.variable",
    ["@tag.delimiter"] = "syntax.punctuation",
    ["@label"] = { link = "@tag" },
    ["@label.go"] = { fg = "accent.note", style = "bold" },
    ["@markup.heading"] = "syntax.markup.heading",
    ["@markup.strong"] = "foreground.strong",
    ["@markup.italic"] = { fg = "foreground.primary", style = "italic" },
    ["@markup.strikethrough"] = { fg = "foreground.primary", style = "strikethrough" },
    ["@markup.underline"] = { link = "Underlined" },
    ["@markup.quote"] = "syntax.keyword",
    ["@markup.math"] = "syntax.keyword",
    ["@markup.environment"] = "syntax.preprocessor",
    ["@markup.environment.name"] = "syntax.function",
    ["@markup.link"] = "foreground.link",
    ["@markup.link.uri"] = "foreground.link",
    ["@markup.link.label"] = { link = "Special" },
    ["@markup.raw"] = "syntax.markup.raw",
    ["@markup.raw.block"] = { link = "@markup.raw" },
    ["@markup.list"] = "accent.quaternary",
    ["@markup.list.checked"] = "git.added",
    ["@markup.list.unchecked"] = "foreground.muted",
    ["@diff.plus"] = { link = "diffAdded" },
    ["@diff.minus"] = { link = "diffRemoved" },
    ["@diff.delta"] = { link = "diffChanged" },

    ["@attribute.java"] = "syntax.annotation",
    ["@constant.builtin.java"] = "syntax.constant",
    ["@constant.builtin.go"] = { fg = "syntax.constant", style = "bold" },
    ["@variable.builtin.java"] = "syntax.builtin",
    ["@type.builtin.java"] = "syntax.builtin",
    ["@function.builtin.java"] = "syntax.function.call",
    ["@function.call.bash"] = { link = "@lsp.type.function" },
    ["@function.builtin.bash"] = "syntax.function.call",
    ["@number.bash"] = {},
    ["@punctuation.bracket.bash"] = { fg = "syntax.string" },
    ["@markup.list.bash"] = { link = "@punctuation.delimiter.bash" },
  }

  buckets.apply_treesitter(groups)

  return groups
end
