local symbol_kind_specs = {
  File = { fg = "accent.primary", bg = "background.editor" },
  Module = { fg = "foreground.primary", bg = "background.editor" },
  Namespace = { fg = "foreground.primary", bg = "background.editor" },
  Package = { fg = "foreground.primary", bg = "background.editor" },
  Class = { fg = "syntax.type", bg = "background.editor", style = "bold" },
  Method = { fg = "syntax.function", bg = "background.editor" },
  Property = { fg = "foreground.primary", bg = "background.editor" },
  Field = { fg = "foreground.primary", bg = "background.editor" },
  Constructor = { fg = "syntax.function", bg = "background.editor" },
  Enum = { fg = "syntax.type", bg = "background.editor", style = "bold" },
  Interface = { fg = "syntax.type", bg = "background.editor", style = "bold" },
  Function = { fg = "syntax.function", bg = "background.editor" },
  Variable = { fg = "foreground.primary", bg = "background.editor" },
  Constant = { fg = "syntax.constant", bg = "background.editor" },
  String = { fg = "syntax.string", bg = "background.editor" },
  Number = { fg = "syntax.constant", bg = "background.editor" },
  Boolean = { fg = "syntax.keyword", bg = "background.editor", style = "bold" },
  Array = { fg = "foreground.primary", bg = "background.editor" },
  Object = { fg = "foreground.primary", bg = "background.editor" },
  Key = { fg = "foreground.primary", bg = "background.editor" },
  Null = { fg = "foreground.muted", bg = "background.editor" },
  EnumMember = { fg = "syntax.constant", bg = "background.editor" },
  Struct = { fg = "syntax.type", bg = "background.editor", style = "bold" },
  Event = { fg = "feedback.warning", bg = "background.editor" },
  Operator = { fg = "syntax.operator", bg = "background.editor" },
  TypeParameter = { fg = "accent.quaternary", bg = "background.editor", style = "bold" },
}

local function add_symbol_kind_groups(groups, prefix)
  for kind, spec in pairs(symbol_kind_specs) do
    groups[prefix .. kind] = spec
  end
end

local M = {}

function M.groups()
  local groups = {
    GitSignsAdd = "git.added",
    GitSignsChange = "git.changed",
    GitSignsDelete = "git.deleted",
    GitSignsAddNr = "git.added",
    GitSignsChangeNr = "git.changed",
    GitSignsDeleteNr = "git.deleted",

    TelescopeNormal = "editor",
    TelescopeBorder = { fg = "border.primary", bg = "background.editor" },
    TelescopeTitle = { fg = "foreground.primary", bg = "background.editor", style = "bold" },
    TelescopePromptNormal = "editor",
    TelescopePromptBorder = { fg = "border.primary", bg = "background.editor" },
    TelescopePromptTitle = { fg = "foreground.primary", bg = "background.editor", style = "bold" },
    TelescopePromptPrefix = { fg = "accent.secondary", bg = "background.editor" },
    TelescopePromptCounter = { fg = "foreground.muted", bg = "background.editor" },
    TelescopeResultsNormal = "editor",
    TelescopeResultsBorder = { fg = "border.primary", bg = "background.editor" },
    TelescopeResultsTitle = { fg = "foreground.muted", bg = "background.editor", style = "bold" },
    TelescopePreviewNormal = "editor",
    TelescopePreviewBorder = { fg = "border.primary", bg = "background.editor" },
    TelescopePreviewTitle = { fg = "foreground.primary", bg = "background.editor", style = "bold" },
    TelescopeSelection = { link = "CursorLine" },
    TelescopeSelectionCaret = "interaction.active",
    TelescopeMultiSelection = { fg = "accent.primary", bg = "background.cursorline" },
    TelescopeMultiIcon = { fg = "accent.primary", bg = "background.cursorline" },
    TelescopeMatching = { link = "Search" },
    TelescopePreviewLine = "reference",
    TelescopePreviewMatch = { fg = "foreground.primary", bg = "background.search", style = "bold" },
    TelescopePreviewPipe = "syntax.operator",
    TelescopePreviewCharDev = "syntax.preprocessor",
    TelescopePreviewDirectory = "entity.directory",
    TelescopePreviewBlock = "syntax.preprocessor",
    TelescopePreviewLink = "foreground.link",
    TelescopePreviewSocket = "accent.tertiary",
    TelescopePreviewRead = "git.added",
    TelescopePreviewWrite = "diagnostic.warn",
    TelescopePreviewExecute = "accent.tertiary",
    TelescopePreviewHyphen = "foreground.muted",
    TelescopePreviewSize = "syntax.number",
    TelescopePreviewUser = "foreground.secondary",
    TelescopePreviewGroup = "foreground.secondary",
    TelescopePreviewDate = "foreground.muted",
    TelescopePreviewMessage = "foreground.muted",
    TelescopePreviewMessageFillchar = { fg = "border.primary" },
    TelescopeResultsComment = "foreground.muted",
    TelescopeResultsIdentifier = "foreground.primary",
    TelescopeResultsLineNr = "foreground.muted",
    TelescopeResultsNumber = "syntax.number",
    TelescopeResultsSpecialComment = { fg = "syntax.comment", style = "bold" },
    TelescopeResultsDiffAdd = "git.added",
    TelescopeResultsDiffChange = "git.changed",
    TelescopeResultsDiffDelete = "git.deleted",
    TelescopeResultsDiffUntracked = "git.untracked",
    TelescopeResultsClass = "syntax.type",
    TelescopeResultsStruct = "syntax.type",
    TelescopeResultsFunction = "syntax.function",
    TelescopeResultsMethod = "syntax.function",
    TelescopeResultsField = "syntax.property",
    TelescopeResultsOperator = "syntax.operator",
    TelescopeResultsConstant = "syntax.constant",
    TelescopeResultsVariable = "syntax.variable",
    TelescopeResultsTierProject = "foreground.primary",
    TelescopeResultsTierStdlib = "accent.quaternary",
    TelescopeResultsTierDep = "foreground.muted",

    NeoTreeNormal = "editor.sidebar",
    NeoTreeNormalNC = "editor.sidebar",
    NeoTreeWinSeparator = { fg = "border.primary", bg = "background.secondary" },
    NeoTreeDirectoryName = "entity.directory",
    NeoTreeDirectoryIcon = "entity.directory.icon",
    NeoTreeFileName = "entity.file",
    NeoTreeRootName = "foreground.strong",
    NeoTreeSymbolicLinkTarget = "foreground.link",
    NeoTreeFileNameOpened = "foreground.strong",
    NeoTreeDimText = "foreground.muted",
    NeoTreeMessage = "foreground.muted",
    NeoTreeModified = "diagnostic.warn",
    NeoTreeGitModified = "git.changed",
    NeoTreeGitAdded = "git.added",
    NeoTreeGitDeleted = "git.deleted",
    NeoTreeGitConflict = "git.conflict",
    NeoTreeGitUntracked = "git.untracked",
    NeoTreeGitIgnored = "git.ignored",
    NeoTreeGitUnstaged = "diagnostic.warn",
    NeoTreeGitStaged = "git.added",
    NeoTreeIndentMarker = { fg = "border.primary" },
    NeoTreeExpander = "foreground.secondary",
    NeoTreeFloatBorder = "float.border",
    NeoTreeFloatTitle = { fg = "foreground.primary", bg = "background.secondary", style = "bold" },
    NeoTreeTitleBar = { fg = "foreground.inverse", bg = "accent.primary", style = "bold" },
    NeoTreeEndOfBuffer = "editor.non.text",
    NeoTreeDotfile = "foreground.muted",

    OilDir = "entity.directory",
    OilDirIcon = "entity.directory.icon",
    OilFile = "entity.file",
    OilLink = "foreground.link",
    OilLinkTarget = "foreground.muted",
    OilCreate = "git.added",
    OilDelete = "git.deleted",
    OilMove = "diagnostic.warn",
    OilCopy = "entity.directory.icon",
    OilPurge = { fg = "feedback.danger", style = "bold" },
    OilChange = "diagnostic.warn",
    OilRestore = "git.added",
    OilTrash = "git.deleted",
    OilTrashSourcePath = "foreground.muted",

    DiffviewNormal = "editor",
    DiffviewCursorLine = "editor.cursorline",
    DiffviewFilePanelTitle = "foreground.strong",
    DiffviewFilePanelCounter = "interaction.match",
    DiffviewFilePanelRootPath = "foreground.muted",
    DiffviewFilePanelPath = "foreground.primary",
    DiffviewFilePanelFileName = "foreground.primary",
    DiffviewFilePanelInsertions = "git.added",
    DiffviewFilePanelDeletions = "git.deleted",
    DiffviewVertSplit = "editor.border",
    DiffviewSignColumn = { fg = "foreground.muted", bg = "background.editor" },
    DiffviewEndOfBuffer = "editor.non.text",
    DiffviewStatusModified = "git.changed",
    DiffviewStatusAdded = "git.added",
    DiffviewStatusDeleted = "git.deleted",
    DiffviewStatusRenamed = "git.changed",
    DiffviewStatusUntracked = "git.untracked",
    DiffviewStatusUnknown = "foreground.muted",
    DiffviewStatusUnmerged = "git.conflict",
    DiffviewStatusBroken = "git.deleted",
    DiffviewStatusCopied = "entity.directory.icon",
    DiffviewStatusTypeChange = "diagnostic.warn",
    DiffviewStatusIgnored = "git.ignored",

    IlluminatedWordText = "reference.illuminated",
    IlluminatedWordRead = "reference.illuminated",
    IlluminatedWordWrite = "reference.illuminated.write",

    CmpItemAbbr = "foreground.primary",
    CmpItemAbbrDeprecated = "foreground.deprecated",
    CmpItemAbbrMatch = "interaction.match",
    CmpItemAbbrMatchFuzzy = "interaction.match",
    CmpItemMenu = "foreground.muted",
    CmpItemKind = "accent.quaternary",
    CmpItemKindDefault = "foreground.secondary",
    CmpItemKindText = "foreground.primary",
    CmpItemKindMethod = "syntax.function",
    CmpItemKindFunction = "syntax.function",
    CmpItemKindConstructor = "syntax.function",
    CmpItemKindField = "syntax.property",
    CmpItemKindVariable = "syntax.variable",
    CmpItemKindClass = "syntax.type",
    CmpItemKindInterface = "syntax.type",
    CmpItemKindModule = "syntax.variable",
    CmpItemKindProperty = "syntax.property",
    CmpItemKindUnit = "syntax.constant",
    CmpItemKindValue = "syntax.constant",
    CmpItemKindEnum = "syntax.type",
    CmpItemKindKeyword = "syntax.keyword",
    CmpItemKindSnippet = "accent.quaternary",
    CmpItemKindColor = "entity.directory.icon",
    CmpItemKindFile = "entity.directory.icon",
    CmpItemKindReference = "entity.directory.icon",
    CmpItemKindFolder = "entity.directory",
    CmpItemKindEnumMember = "syntax.constant",
    CmpItemKindConstant = "syntax.constant",
    CmpItemKindStruct = "syntax.type",
    CmpItemKindEvent = "diagnostic.warn",
    CmpItemKindOperator = "syntax.operator",
    CmpItemKindTypeParameter = "syntax.type.parameter",
    CmpDocumentation = "float",
    CmpDocumentationBorder = "float.border",

    MasonNormal = "editor",
    MasonHeader = { fg = "foreground.inverse", bg = "accent.primary", style = "bold" },
    MasonHeaderSecondary = { fg = "foreground.inverse", bg = "accent.secondary", style = "bold" },
    MasonHeading = "foreground.strong",
    MasonMuted = "foreground.muted",
    MasonMutedBlock = { fg = "foreground.muted", bg = "background.secondary" },
    MasonMutedBlockBold = { fg = "foreground.secondary", bg = "background.secondary", style = "bold" },
    MasonHighlight = "entity.directory.icon",
    MasonHighlightBlock = { fg = "foreground.inverse", bg = "accent.primary" },
    MasonHighlightBlockBold = { fg = "foreground.inverse", bg = "accent.primary", style = "bold" },
    MasonHighlightSecondary = "syntax.keyword",
    MasonHighlightBlockSecondary = { fg = "foreground.inverse", bg = "accent.secondary" },
    MasonHighlightBlockBoldSecondary = { fg = "foreground.inverse", bg = "accent.secondary", style = "bold" },
    MasonLink = "foreground.link",
    MasonError = "diagnostic.error",
    MasonWarning = "diagnostic.warn",

    LazyNormal = "editor",
    LazyButton = { fg = "foreground.primary", bg = "background.secondary" },
    LazyButtonActive = { fg = "foreground.primary", bg = "background.selection", style = "bold" },
    LazyH1 = { fg = "foreground.inverse", bg = "accent.primary", style = "bold" },
    LazyH2 = "foreground.strong",
    LazySpecial = "accent.quaternary",
    LazyReasonCmd = "entity.directory.icon",
    LazyReasonEvent = "diagnostic.warn",
    LazyReasonFt = "accent.tertiary",
    LazyReasonImport = "syntax.keyword",
    LazyReasonKeys = "syntax.constant",
    LazyReasonPlugin = "accent.quaternary",
    LazyReasonRuntime = "foreground.secondary",
    LazyReasonSource = "git.added",
    LazyReasonStart = "entity.directory.icon",
    LazyReasonTask = "diagnostic.warn",
    LazyTaskOutput = "foreground.secondary",
    LazyCommit = "entity.directory.icon",
    LazyCommitIssue = "syntax.keyword",
    LazyCommitScope = "foreground.secondary",
    LazyCommitType = "syntax.constant",
    LazyDir = "entity.directory.icon",
    LazyUrl = "foreground.link",
    LazyValue = "syntax.constant",
    LazyProgressDone = "git.added",
    LazyProgressTodo = { fg = "border.primary" },

    DbUtilsDirectiveKey = "foreground.muted",
    DbUtilsDirectiveValue = "syntax.keyword",
    DbResultsBorder = "foreground.muted",
    DbResultsHeader = "syntax.keyword",
    DbResultsNull = { fg = "foreground.muted", style = "italic" },
    FieldMarker = { style = "underline" },

    WinBar = { fg = "accent.primary", bg = "background.editor", style = "bold" },
    WinBarNC = { fg = "accent.primary", bg = "background.editor", style = "bold" },

    DapBreakpoint = "debug.breakpoint",
    DapBreakpointCondition = "debug.condition",
    DapBreakpointRejected = "debug.rejected",
    DapLogPoint = "diagnostic.hint",
    DapStopped = "debug.stopped",
    DapUIVariable = "syntax.variable",
    DapUIScope = { fg = "accent.tertiary", style = "bold" },
    DapUIType = "accent.quaternary",
    DapUIValue = "foreground.primary",
    DapUIModifiedValue = "interaction.match",
    DapUIDecoration = { fg = "border.primary" },
    DapUIThread = "git.added",
    DapUIStoppedThread = "diagnostic.info",
    DapUIFrameName = "foreground.primary",
    DapUISource = "entity.directory.icon",
    DapUILineNumber = "syntax.number",
    DapUIFloatBorder = "float.border",
    DapUIWatchesEmpty = "foreground.muted",
    DapUIWatchesValue = "foreground.primary",
    DapUIWatchesError = "diagnostic.error",
    DapUIBreakpointsPath = "entity.directory.icon",
    DapUIBreakpointsInfo = "git.added",
    DapUIBreakpointsCurrentLine = "interaction.match",
    DapUIBreakpointsLine = "foreground.primary",
    DapUIBreakpointsDisabledLine = "foreground.muted",
    DapUICurrentFrameName = "interaction.match",
    DapUIStepOver = "diagnostic.info",
    DapUIStepInto = "diagnostic.info",
    DapUIStepBack = "diagnostic.info",
    DapUIStepOut = "diagnostic.info",
    DapUIStop = "debug.breakpoint",
    DapUIPlayPause = "git.added",
    DapUIRestart = "git.added",
    DapUIUnavailable = "foreground.muted",
    DapUIWinSelect = "interaction.match",
    DapUIEndofBuffer = "editor.non.text",
    DapUIPlayPauseNC = "git.added",
    DapUIRestartNC = "git.added",
    DapUIStopNC = "debug.breakpoint",

    BarbecueNormal = { fg = "foreground.primary", bg = "background.editor" },
    BarbecueEllipsis = { fg = "foreground.muted", bg = "background.editor" },
    BarbecueSeparator = { fg = "foreground.secondary", bg = "background.editor" },
    BarbecueModified = { fg = "feedback.warning", bg = "background.editor" },
    BarbecueDirname = { fg = "foreground.muted", bg = "background.editor" },
    BarbecueBasename = { fg = "foreground.primary", bg = "background.editor", style = "bold" },
    BarbecueContext = { fg = "foreground.primary", bg = "background.editor" },

    NavicText = { fg = "foreground.primary", bg = "background.editor" },
    NavicSeparator = { fg = "foreground.secondary", bg = "background.editor" },
  }

  add_symbol_kind_groups(groups, "BarbecueContext")
  add_symbol_kind_groups(groups, "NavicIcons")

  return groups
end

return M
