local M = {}

function M.groups()
  return {
    -- Shared window chrome
    SnacksNormal = "editor",
    SnacksNormalNC = "editor.inactive",
    SnacksWinBar = "foreground.strong",
    SnacksWinBarNC = "foreground.muted",
    SnacksWinSeparator = "editor.border",
    SnacksTitle = "foreground.strong",
    SnacksFooter = "foreground.muted",
    SnacksFooterKey = "interaction.match",
    SnacksFooterDesc = "foreground.muted",
    SnacksWinKey = "interaction.match",
    SnacksWinKeySep = "foreground.muted",
    SnacksWinKeyDesc = "foreground.secondary",

    -- Picker and explorer (the explorer is a picker source)
    SnacksPicker = "editor",
    SnacksPickerNormal = "editor",
    SnacksPickerBorder = { fg = "border.primary", bg = "background.editor" },
    SnacksPickerTitle = { fg = "foreground.primary", bg = "background.editor", style = "bold" },
    SnacksPickerFooter = "foreground.muted",
    SnacksPickerCursorLine = "editor.cursorline",
    SnacksPickerInput = "editor",
    SnacksPickerInputBorder = { fg = "border.focus", bg = "background.editor" },
    SnacksPickerInputTitle = { fg = "interaction.focus", bg = "background.editor", style = "bold" },
    SnacksPickerList = "editor",
    SnacksPickerListBorder = { fg = "border.primary", bg = "background.editor" },
    SnacksPickerListTitle = "foreground.strong",
    SnacksPickerPreview = "editor",
    SnacksPickerPreviewBorder = { fg = "border.primary", bg = "background.editor" },
    SnacksPickerPreviewTitle = "foreground.strong",
    SnacksPickerListCursorLine = "editor.cursorline",
    SnacksPickerPreviewCursorLine = "editor.cursorline",
    SnacksPickerMatch = "interaction.match",
    SnacksPickerSearch = "search",
    SnacksPickerPrompt = { fg = "interaction.active", style = "bold" },
    SnacksPickerInputSearch = "syntax.keyword",
    SnacksPickerSpecial = "accent.quaternary",
    SnacksPickerToggle = "diagnostic.info",
    SnacksPickerDimmed = "foreground.muted",
    SnacksPickerFile = "entity.file",
    SnacksPickerDirectory = "entity.directory",
    SnacksPickerDir = "foreground.muted",
    SnacksPickerPathHidden = "foreground.muted",
    SnacksPickerPathIgnored = "git.ignored",
    SnacksPickerLink = "foreground.link",
    SnacksPickerLinkBroken = "diagnostic.error",
    SnacksPickerTree = "editor.line.number",
    SnacksPickerSelected = "interaction.match",
    SnacksPickerUnselected = "foreground.muted",
    SnacksPickerIdx = "syntax.number",
    SnacksPickerDesc = "foreground.muted",
    SnacksPickerDelim = "syntax.punctuation",
    SnacksPickerSpinner = "interaction.active",
    SnacksPickerGitStatusAdded = "git.added",
    SnacksPickerGitStatusModified = "git.changed",
    SnacksPickerGitStatusDeleted = "git.deleted",
    SnacksPickerGitStatusRenamed = "git.changed",
    SnacksPickerGitStatusCopied = "git.changed",
    SnacksPickerGitStatusUntracked = "git.untracked",
    SnacksPickerGitStatusIgnored = "git.ignored",
    SnacksPickerGitStatusUnmerged = "git.conflict",
    SnacksPickerGitStatusStaged = "git.added",

    -- Dashboard
    SnacksDashboardNormal = "editor",
    SnacksDashboardHeader = "accent.primary",
    SnacksDashboardFooter = "foreground.muted",
    SnacksDashboardTitle = "foreground.strong",
    SnacksDashboardIcon = "accent.quaternary",
    SnacksDashboardKey = "interaction.match",
    SnacksDashboardDesc = "foreground.secondary",
    SnacksDashboardFile = "entity.file",
    SnacksDashboardDir = "entity.directory",
    SnacksDashboardSpecial = "accent.literal",

    -- Input and notifications
    SnacksInputNormal = "float",
    SnacksInputBorder = "float.border",
    SnacksInputTitle = "foreground.strong",
    SnacksInputPrompt = "foreground.strong",
    SnacksInputIcon = "diagnostic.hint",
    SnacksNotifierHistory = "editor",
    SnacksNotifierHistoryTitle = "foreground.strong",
    SnacksNotifierHistoryDateTime = "foreground.muted",
    SnacksNotifierMinimal = "float",

    SnacksNotifierInfo = "float",
    SnacksNotifierIconInfo = "diagnostic.info",
    SnacksNotifierBorderInfo = "diagnostic.info",
    SnacksNotifierTitleInfo = "diagnostic.info",
    SnacksNotifierFooterInfo = "diagnostic.info",
    SnacksNotifierWarn = "float",
    SnacksNotifierIconWarn = "diagnostic.warn",
    SnacksNotifierBorderWarn = "diagnostic.warn",
    SnacksNotifierTitleWarn = "diagnostic.warn",
    SnacksNotifierFooterWarn = "diagnostic.warn",
    SnacksNotifierError = "float",
    SnacksNotifierIconError = "diagnostic.error",
    SnacksNotifierBorderError = "diagnostic.error",
    SnacksNotifierTitleError = "diagnostic.error",
    SnacksNotifierFooterError = "diagnostic.error",
    SnacksNotifierDebug = "float",
    SnacksNotifierIconDebug = "foreground.muted",
    SnacksNotifierBorderDebug = "foreground.muted",
    SnacksNotifierTitleDebug = "foreground.muted",
    SnacksNotifierFooterDebug = "foreground.muted",
    SnacksNotifierTrace = "float",
    SnacksNotifierIconTrace = "foreground.muted",
    SnacksNotifierBorderTrace = "foreground.muted",
    SnacksNotifierTitleTrace = "foreground.muted",
    SnacksNotifierFooterTrace = "foreground.muted",

    -- Indentation, scope, scratch and zen
    SnacksIndent = "editor.whitespace",
    SnacksIndentScope = { fg = "accent.tertiary" },
    SnacksIndentChunk = "interaction.active",
    SnacksScratchTitle = "foreground.strong",
    SnacksZenIcon = "diagnostic.warn",
  }
end

return M
