return {
  editor = { fg = "foreground.primary", bg = "background.editor" },
  ["editor.inactive"] = { fg = "foreground.primary", bg = "background.editor" },
  ["editor.sidebar"] = { fg = "foreground.primary", bg = "background.sidebar" },
  ["editor.cursor"] = { fg = "background.editor", bg = "foreground.primary" },
  ["editor.cursorline"] = { inherit = false, bg = "background.cursorline" },
  ["editor.cursorline.number"] = { fg = "foreground.primary", bg = "background.cursorline", style = "bold" },
  ["editor.line.number"] = { fg = "foreground.muted" },
  ["editor.non.text"] = { fg = "background.tertiary" },
  ["editor.whitespace"] = { fg = "border.primary" },
  ["editor.border"] = { fg = "border.primary" },
  ["editor.fold"] = { fg = "foreground.secondary", bg = "background.secondary" },
  ["editor.color.column"] = { inherit = false, bg = "background.feedback.danger" },

  float = { fg = "foreground.primary", bg = "background.float" },
  ["float.border"] = { fg = "border.primary", bg = "background.float" },

  popup = { fg = "foreground.primary", bg = "background.popup" },
  ["popup.selected"] = { bg = "background.popup.selected" },
  ["popup.scrollbar"] = { bg = "background.popup.scrollbar" },
  ["popup.thumb"] = { bg = "background.popup.thumb" },

  foreground = { fg = "foreground.primary" },
  ["foreground.secondary"] = { fg = "foreground.secondary" },
  ["foreground.muted"] = { fg = "foreground.muted" },
  ["foreground.strong"] = { fg = "foreground.primary", style = "bold" },
  ["foreground.link"] = { fg = "foreground.link", style = "underline" },
  ["foreground.deprecated"] = { fg = "foreground.deprecated", style = "strikethrough" },

  accent = { fg = "accent.primary" },
  ["accent.secondary"] = { fg = "accent.secondary" },
  ["accent.tertiary"] = { fg = "accent.tertiary" },
  ["accent.quaternary"] = { fg = "accent.quaternary" },
  ["accent.literal"] = { fg = "accent.literal" },
  ["accent.note"] = { fg = "accent.note" },

  feedback = { fg = "feedback.info" },
  ["feedback.info"] = { fg = "feedback.info" },
  ["feedback.hint"] = { fg = "feedback.hint" },
  ["feedback.success"] = { fg = "feedback.success" },
  ["feedback.warning"] = { fg = "feedback.warning" },
  ["feedback.danger"] = { fg = "feedback.danger" },

  entity = { fg = "foreground.primary" },
  ["entity.file"] = { fg = "entity.file" },
  ["entity.directory"] = { fg = "entity.directory", style = "bold" },
  ["entity.directory.icon"] = { fg = "entity.directory.icon" },

  interaction = { fg = "interaction.active" },
  ["interaction.active"] = { fg = "interaction.active", bg = "interaction.hover", style = "bold" },
  ["interaction.match"] = { fg = "interaction.match", style = "bold" },
  ["interaction.selected"] = { bg = "interaction.selected" },

  syntax = { fg = "syntax.operator" },
  ["syntax.comment"] = { fg = "syntax.comment" },
  ["syntax.keyword"] = { fg = "syntax.keyword.primary", style = "bold" },
  ["syntax.keyword.primary"] = { fg = "syntax.keyword.primary", style = "bold" },
  ["syntax.keyword.secondary"] = { fg = "syntax.keyword.secondary", style = "bold" },
  ["syntax.keyword.directive"] = { fg = "syntax.keyword.directive", style = "bold" },
  ["syntax.annotation"] = { fg = "syntax.annotation", style = "bold" },
  ["syntax.type"] = { fg = "syntax.type", style = "bold" },
  ["syntax.type.definition"] = { fg = "syntax.type", style = "bold" },
  ["syntax.type.parameter"] = { fg = "syntax.type.parameter" },
  ["syntax.function"] = { fg = "syntax.function" },
  ["syntax.function.call"] = { fg = "syntax.function.call" },
  ["syntax.function.definition"] = { fg = "syntax.function.definition", style = "bold" },
  ["syntax.variable"] = { fg = "syntax.variable" },
  ["syntax.property"] = { fg = "syntax.property" },
  ["syntax.constant"] = { fg = "syntax.constant" },
  ["syntax.string"] = { fg = "syntax.string" },
  ["syntax.number"] = { fg = "syntax.number" },
  ["syntax.boolean"] = { fg = "syntax.boolean", style = "bold" },
  ["syntax.operator"] = { fg = "syntax.operator" },
  ["syntax.punctuation"] = { fg = "syntax.punctuation" },
  ["syntax.bracket"] = { fg = "syntax.bracket" },
  ["syntax.preprocessor"] = { fg = "syntax.preprocessor" },
  ["syntax.builtin"] = { fg = "syntax.builtin", style = "bold" },
  ["syntax.tag"] = { fg = "syntax.tag" },
  ["syntax.markup.heading"] = { fg = "syntax.markup.heading", style = "bold" },
  ["syntax.markup.raw"] = { fg = "syntax.markup.raw" },

  search = { bg = "background.search" },
  ["search.active"] = { fg = "foreground.primary", bg = "background.search.active", style = "bold" },
  ["search.match.paren"] = { bg = "interaction.selected", style = "bold" },

  visual = { bg = "interaction.selected" },

  diagnostic = { fg = "feedback.info" },
  ["diagnostic.error"] = { fg = "feedback.danger" },
  ["diagnostic.warn"] = { fg = "feedback.warning" },
  ["diagnostic.info"] = { fg = "feedback.info" },
  ["diagnostic.hint"] = { fg = "feedback.hint" },
  ["diagnostic.ok"] = { fg = "feedback.success" },

  diff = { fg = "foreground.primary" },
  ["diff.add"] = { fg = "vcs.added", bg = "background.feedback.success" },
  ["diff.change"] = { fg = "vcs.changed", bg = "background.feedback.warning" },
  ["diff.delete"] = { fg = "vcs.deleted", bg = "background.feedback.danger" },
  ["diff.text"] = { bg = "background.feedback.info" },

  git = { fg = "foreground.primary" },
  ["git.added"] = { fg = "vcs.added" },
  ["git.changed"] = { fg = "vcs.changed" },
  ["git.deleted"] = { fg = "vcs.deleted" },
  ["git.untracked"] = { fg = "vcs.untracked" },
  ["git.conflict"] = { fg = "feedback.danger", style = "bold" },
  ["git.ignored"] = { fg = "foreground.muted" },

  message = { fg = "foreground.primary", style = "bold" },
  ["message.mode"] = { fg = "interaction.active", style = "bold" },
  ["message.error"] = { fg = "feedback.danger", style = "bold" },
  ["message.question"] = { fg = "feedback.hint", style = "bold" },
  ["message.warning"] = { fg = "foreground.primary", style = "bold" },

  reference = { bg = "background.reference" },
  ["reference.write"] = { bg = "background.reference.write" },
  ["reference.illuminated"] = { bg = "background.reference.subtle" },
  ["reference.illuminated.write"] = { bg = "background.reference.write" },

  chrome = { fg = "foreground.primary", bg = "chrome.base" },
  ["chrome.inactive"] = { fg = "foreground.muted", bg = "chrome.inactive" },
  ["chrome.mode.normal"] = { fg = "foreground.inverse", bg = "chrome.mode.normal", style = "bold" },
  ["chrome.mode.insert"] = { fg = "foreground.inverse", bg = "chrome.mode.insert", style = "bold" },
  ["chrome.mode.visual"] = { fg = "foreground.inverse", bg = "chrome.mode.visual", style = "bold" },
  ["chrome.mode.replace"] = { fg = "foreground.inverse", bg = "chrome.mode.replace", style = "bold" },
  ["chrome.mode.command"] = { fg = "foreground.inverse", bg = "chrome.mode.command", style = "bold" },

  debug = { fg = "feedback.info" },
  ["debug.breakpoint"] = { fg = "feedback.danger" },
  ["debug.condition"] = { fg = "feedback.warning" },
  ["debug.rejected"] = { fg = "foreground.muted" },
  ["debug.stopped"] = { fg = "feedback.info", style = "bold" },
}
